### ISSUE TITLE
erro na configuração do BASE_PATH trava carregamento dos assets da página

### ISSUE THREAD

**Issue by rogeriopradoj** [PHPSP/php-guide-pt_BR#3]

**Comment by rogeriopradoj** [comment]
@nawarian, vi que você começou o trabalho na #2 , mas infelizmente não é o suficiente (você pode ver que o link das páginas que estão no menu não funcionam...

O melhor eu acredito é: definir no [_config.yml](https://github.com/PHPSP/php-guide-pt_BR/blob/gh-pages/_config.yml#L37)

``` md
BASE_PATH = '/php-guide-pt_BR'
```

... conforme [manual do jekyll](http://jekyllrb.com/docs/github-pages/) e do [jekyll-bootstrap](http://jekyllbootstrap.com/usage/blog-configuration.html).

E depois ir de uma das duas opções:
1) retirar todas as barras (/) de todos os links e trocar por {{BASE_PATH}}/ em cada um deles
2) retirar todas as barras (/) de todos os links e trocar por apenas uma tag `<base href="{{BASE_PATH}}">` no topo do template!

**Comment by nawarian** [comment]
Sim sim, estou resolvendo isto neste momento.
Obrigado pelo toque

**Comment by rogeriopradoj** [comment]
@nawarian , melhor:
- não usar o base_path (que para funcionar tem que ficar o nome gigante: `{{ site.JB.BASE_PATH }}` ).
- usar o baseurl (para funcionar `{{ site.baseurl }}` )

**Comment by rogeriopradoj** [comment]
Dentro das páginas, os menus com âncoras internas não está funcionando. O PR #10 resolve isso.
